### ISSUE TITLE
cmake ignores HDF5_DIR option

### ISSUE THREAD

**Issue by khou2020** [HDFGroup/vol-tests#19]
Neither using -DHDF5_DIR nor set HDF5_DIR as environment variable works.

$ cmake -DHDF5_DIR=${HOME}/.local/hdf5/1.13.0 ..
-- The C compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- GCC detected, setting additional flags
-- Could NOT find HDF5 (missing: HDF5_DIR)

$ ls ${HOME}/.local/hdf5/1.13.0/lib
libhdf5.a  libhdf5.la  libhdf5.settings  libhdf5.so  libhdf5.so.300  libhdf5.so.300.0.0  libhdf5_hl.a  libhdf5_hl.la  libhdf5_hl.so  libhdf5_hl.so.300  libhdf5_hl.so.300.0.0

$ ls ${HOME}/.local/hdf5/1.13.0/include/
H5ACpublic.h  H5Dpublic.h    H5FDcore.h     H5FDlog.h     H5FDpublic.h    H5FDwindows.h  H5Ipublic.h   H5MMpublic.h  H5PTpublic.h  H5TSdevelop.h             H5VLnative.h    H5api_adpt.h  hdf5.h
H5Apublic.h   H5ESdevelop.h  H5FDdevelop.h  H5FDmirror.h  H5FDros3.h      H5Fpublic.h    H5LDpublic.h  H5Mpublic.h   H5Ppublic.h   H5Tdevelop.h              H5VLpassthru.h  H5overflow.h  hdf5_hl.h
H5Cpublic.h   H5ESpublic.h   H5FDdirect.h   H5FDmpi.h     H5FDsec2.h      H5Gpublic.h    H5LTpublic.h  H5Opublic.h   H5Rpublic.h   H5Tpublic.h               H5VLpublic.h    H5pubconf.h
H5DOpublic.h  H5Epubgen.h    H5FDfamily.h   H5FDmpio.h    H5FDsplitter.h  H5IMpublic.h   H5Ldevelop.h  H5PLextern.h  H5Spublic.h   H5VLconnector.h           H5Zdevelop.h    H5public.h
H5DSpublic.h  H5Epublic.h    H5FDhdfs.h     H5FDmulti.h   H5FDstdio.h     H5Idevelop.h   H5Lpublic.h   H5PLpublic.h  H5TBpublic.h  H5VLconnector_passthru.h  H5Zpublic.h     H5version.h

**Comment by wkliao** [comment]
Any plan to update this issue?
We are testing our VOL implementation.

**Comment by wkliao** [comment]
PR #20 fixes this issue.

**Comment by jhendersonHDF** [comment]
> PR #20 fixes this issue.

Thanks for the fix @wkliao!
